language: python
python:
  - "3.6"

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest
    - stage: deploy
      script:
        - echo Deploying to PyPI...

before_deploy:
  # User and password environment variables are set as hidden variables through
  # the web interface in the project settings.
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - poetry build

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
