language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to install dependencies
install:
  - poetry install
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
