language: python
python:
  - "3.6"

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script:
        - poetry install -v
        - pytest
    - stage: deploy
      script:
        - poetry config pypi-token.pypi $PYPI_TOKEN
        - poetry build
        - poetry publish

install:
  - pip install --upgrade pip
  - pip install poetry

